### ISSUE TITLE
[Urgent Help] Slow Performance with huge resource usage

### ISSUE THREAD

**Issue by gopi0202** [Altinity/ClickHouse#293]
Hi,

I am new to Clickhouse and I am raising to get an urgent help since I am implementing a big system using Clickhouse.

- CH version - 23.3.8.22.altinitystable
- Machine - centos79
- CPU - 8
- Nodes - 20
- Memory - 32 GB
- Shards - 5

Table Structure- ReplicatedMergeTree

`CREATE TABLE table ON CLUSTER '{cluster}'
(
    `col1` INT(),
    `col2` INT(),
    `col3` INT(),
    `col4` INT(),
    `time` DateTime,
    `col5` FLOAT(64),
    `col6` INT()
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{cluster}/{shard}/<>/<>', '{replica}')
ORDER BY (col1, toYYYYMMDD(time), col2, col3, col4)
PARTITION BY (toYYYYMMDD(time))
PRIMARY KEY (col1)`

Select Query -

`SELECT col1, col2, col3, col4, time, col5, col6  FROM table WHERE col1 = 30 AND col2 = 11 ORDER BY time LIMIT 10 OFFSET 1`

I am trying to hit a huge request with this query to CH cluster and the CPU is using around 80% of each nodes and my response time seems to be around 40 ms in each nodes.

I have connected CH to an golang API but my QPS of the API seems very less with max of 5K with big API and CH cluster resources.

I am using an external load balancer to clickhouse tcp client connection with 9000 port.
I feel the response time seems very less and I want to have a 100k qps with the system.
Am I aiming too much with this resources?

Do I need more resources for this usecase.
But I have seen people getting maximum performance with one or two servers.

Please help me to increase the performance or let me know If I am missing something!
Thanks in Advance!

**Comment by filimonov** [comment]
Most probably your query can not filter data efficiently by conditions `WHERE col1 = 30 AND col2 = 11`,  so further ordering (`ORDER BY time`) need to order significant amout of rows. 

It it's the only query you need to run againt that table you can use different order by for the table, to map it to the query. 

I.e. 
```
PARTITION BY (toYYYYMMDD(time)) PRIMARY KEY (col1, col2, time)
```

And add some time contition into your query to eliminate some partitions. 



P.S. That project is not intended to debug schema/queries issues.
