### ISSUE TITLE
Static jwks authentication is failing on 24.8

### ISSUE THREAD

**Issue by alsugiliazova** [Altinity/ClickHouse#547]
```sql
CREATE USER jwt_user_d54bc689_b674_11ef_a7f4_b3bf52bd0986 IDENTIFIED WITH JWT CLAIMS '{}'
```
```xml
<clickhouse>
    <jwt_validators>
        <jwks_with_RS256>
            <static_jwks>{"keys": [{"kty": "RSA", "alg": "RS256", "kid": "some_key_id_d54bc69a_b674_11ef_a7f4_b3bf52bd0986", "n": "w-qmSEoxcBR9OwuFLytY_4tbS9Lu-3KKi9PRdIeZ1bBySynH-qZ5eqsAfgzxvDu73M6PKAQbtH6X4HVi9BoYoAUTYM1cuJ3tvyVdqTNZTgdXUSJzoV2IF1_2viWFCtz78r5FmOcq7umBgl5swaEZqvbu0lHTc7SvrqOXNOdUzR_8t6qAxrv5fXFjrgJIq4cMP_My3adHly1rd347bUbqVJfHcv10xUn-gLErpMoeVcS9vvnrT-skgK5MXzWUfmkHNH4AUGh3axL6P9CMbRTARta1b2HGXxQx7nq9-MmFfsMs7Z--8jXFuRcNtkMG_yAjP7CPuSPNq5YK9TEq6U-udQ", "e": "AQAB"}]}</static_jwks>
        </jwks_with_RS256>
    </jwt_validators>
</clickhouse>
```
`
echo -e "SELECT currentUser()" | clickhouse client -n --jwt "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6InNvbWVfa2V5X2lkX2Q1NGJjNjlhX2I2NzRfMTFlZl9hN2Y0X2IzYmY1MmJkMDk4NiJ9.eyJzdWIiOiJqd3RfdXNlcl9kNTRiYzY4OV9iNjc0XzExZWZfYTdmNF9iM2JmNTJiZDA5ODYifQ.EYJ3Carjlh5IhwwAMvQLhUklBy1QZA5awgDtqPdlJj2elPyksNnWmCArZsmmisdivQLZe4fn6K5iQCnPbJitvaX5C0Bazv13pggwDB-g8IJ_-yToMphmXZ1z0qwVY5nfFldxPKBhMhcT1Ez_EhOsZ34fAB-GaN_YXdKS8_hZR-ImfzrlNtUHEYvWD1HKmLpoGAUKwAw3djNcBXsfYQ5u0bebnnhXE9lqJ1Pa4CVHMB-e-GciZkodoFBaI62OZexYc6Xqd9usjlBk2VC8TVF8P0yqnQr7w-NgaYCM1hiwlZ6WdScmjmnctilmfveclPBUnjSpkxgzrqut5Nv-L-MkxA"
`

Output:
```
Code: 516. DB::Exception: Received from localhost:9000. DB::Exception: jwt_user_d54bc689_b674_11ef_a7f4_b3bf52bd0986: Authentication failed: password is incorrect, or there is no user with such name.. (AUTHENTICATION_FAILED)
```
Using build from this commit https://github.com/Altinity/ClickHouse/pull/540/commits/975eb0854d6d8cb7a00588ccb8ea4a1797e82a9b

This test passed on 24.3 builds.

**Comment by alsugiliazova** [comment]
@zvonand

**Comment by zvonand** [comment]
https://github.com/Altinity/ClickHouse/pull/540/commits/316a786db3d21d2df1c6b1bb674e280d18e0f125
